platform:
    - x86
    - x64

environment:
    matrix:
        - VSVER: 14

configuration:
    - plain
    
before_build:
    - ps: >-
        If ($env:Platform -Match "x86") {
            $env:VCVARS_PLATFORM="x86"
        } Else {
            $env:VCVARS_PLATFORM="amd64"
        }
    - ps: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
    - call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" %VCVARS_PLATFORM%
    - git submodule update --init

build_script:
  - cmake -H. -B_build
  - cmake --build _build
  - cd _build
  - ctest 
